In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# Loading all datasets

circuits = pd.read_csv('Dataset/circuits.csv')
constructor_results = pd.read_csv('Dataset/constructor_results.csv')
constructor_standings = pd.read_csv('Dataset/constructor_standings.csv')
constructors = pd.read_csv('Dataset/constructors.csv')
driver_standings = pd.read_csv('Dataset/driver_standings.csv')
drivers = pd.read_csv('Dataset/drivers.csv')
lap_times = pd.read_csv('Dataset/lap_times.csv')
pit_stops = pd.read_csv('Dataset/pit_stops.csv')
qualifying = pd.read_csv('Dataset/qualifying.csv')
races = pd.read_csv('Dataset/races.csv')
results = pd.read_csv('Dataset/results.csv')
seasons = pd.read_csv('Dataset/seasons.csv')
sprint_results = pd.read_csv('Dataset/sprint_results.csv')
status = pd.read_csv('Dataset/status.csv')

In [3]:
# Checking is duplicate data exists

print(circuits.duplicated().sum())
print(constructor_results.duplicated().sum())
print(constructor_standings.duplicated().sum())
print(constructors.duplicated().sum())
print(driver_standings.duplicated().sum())
print(drivers.duplicated().sum())
print(lap_times.duplicated().sum())
print(pit_stops.duplicated().sum())
print(qualifying.duplicated().sum())
print(races.duplicated().sum())
print(results.duplicated().sum())
print(seasons.duplicated().sum())
print(sprint_results.duplicated().sum())
print(status.duplicated().sum())

0
0
0
0
0
0
0
0
0
0
0
0
0
0
0

In [4]:
# Checking for null (NaN) values

print(circuits.isnull().sum())
print(constructor_results.isnull().sum())
print(constructor_standings.isnull().sum())
print(constructors.isnull().sum())
print(driver_standings.isnull().sum())
print(drivers.isnull().sum())
print(lap_times.isnull().sum())
print(pit_stops.isnull().sum())
print(qualifying.isnull().sum())            # Only this contains NaN values 
print(races.isnull().sum())
print(results.isnull().sum())
print(seasons.isnull().sum())
print(sprint_results.isnull().sum())
print(status.isnull().sum())

circuitId     0
circuitRef    0
name          0
location      0
country       0
lat           0
lng           0
alt           0
url           0
dtype: int64
constructorResultsId    0
raceId                  0
constructorId           0
points                  0
status                  0
dtype: int64
constructorStandingsId    0
raceId                    0
constructorId             0
points                    0
position                  0
positionText              0
wins                      0
dtype: int64
constructorId     0
constructorRef    0
name              0
nationality       0
url               0
dtype: int64
driverStandingsId    0
raceId               0
driverId             0
points               0
position             0
positionText         0
wins                 0
dtype: int64
driverStandingsId    0
raceId               0
driverId             0
points               0
position             0
positionText         0
wins                 0
dtype: int64
driverId       0
driverRef      0
number         0
code           0
forename       0
surname        0
dob            0
nationality    0
url            0
dtype: int64
raceId          0
driverId        0
lap             0
position        0
time            0
milliseconds    0
dtype: int64
raceId          0
driverId        0
stop            0
lap             0
time            0
duration        0
milliseconds    0
dtype: int64
qualifyId         0
raceId            0
driverId          0
constructorId     0
number            0
position          0
q1                0
q2               22
q3               46
dtype: int64
raceId         0
year           0
round          0
circuitId      0
name           0
date           0
time           0
url            0
fp1_date       0
fp1_time       0
fp2_date       0
fp2_time       0
fp3_date       0
fp3_time       0
quali_date     0
quali_time     0
sprint_date    0
sprint_time    0
dtype: int64
resultId           0
raceId             0
driverId           0
constructorId      0
number             0
grid               0
position           0
positionText       0
positionOrder      0
points             0
laps               0
time               0
milliseconds       0
fastestLap         0
rank               0
fastestLapTime     0
fastestLapSpeed    0
statusId           0
dtype: int64
year    0
url     0
dtype: int64
resultId          0
raceId            0
driverId          0
constructorId     0
number            0
grid              0
position          0
positionText      0
positionOrder     0
points            0
laps              0
time              0
milliseconds      0
fastestLap        0
fastestLapTime    0
statusId          0
dtype: int64
statusId    0
status      0
dtype: int64

In [5]:
# Function for replacing all the '\N' with "NA" throughout everywhere!

def clean_backslash_n(df):
    return df.replace('\\N', 'NA', inplace=True)

In [6]:
# 1. circuits.csv
# There's no need of 'lat,lng,alt,url' 


circuits_new = circuits.copy()
circuits_new.drop(columns=['lat', 'lng', 'alt', 'url'], inplace=True)
clean_backslash_n(circuits_new)

,circuitId,circuitRef,name,location,country
0,1,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia
1,2,sepang,Sepang International Circuit,Kuala Lumpur,Malaysia
2,3,bahrain,Bahrain International Circuit,Sakhir,Bahrain
3,4,catalunya,Circuit de Barcelona-Catalunya,Montmeló,Spain
4,5,istanbul,Istanbul Park,Istanbul,Turkey
...,...,...,...,...,...
72,75,portimao,Autódromo Internacional do Algarve,Portimão,Portugal
73,76,mugello,Autodromo Internazionale del Mugello,Mugello,Italy
74,77,jeddah,Jeddah Corniche Circuit,Jeddah,Saudi Arabia
75,78,losail,Losail International Circuit,Al Daayen,Qatar
76,79,miami,Miami International Autodrome,Miami,USA

In [7]:
# 2. constructor_results.csv
# There's '\N' in entire of 'Status' column
# There's no need of it


constructor_results_new = constructor_results.copy()
constructor_results_new.drop(columns=['status'], inplace=True)
clean_backslash_n(constructor_results_new)

       constructorResultsId  raceId  constructorId  points
0                         1      18              1    14.0
1                         2      18              2     8.0
2                         3      18              3     9.0
3                         4      18              4     5.0
4                         5      18              5     2.0
...                     ...     ...            ...     ...
12620                 17125    1144            210     4.0
12621                 17126    1144            117     2.0
12622                 17127    1144              3     0.0
12623                 17128    1144            215     0.0
12624                 17129    1144             15     0.0

[12625 rows x 4 columns]

In [8]:
# 3. constructor_standings.csv
# Nothing to change here!


constructor_standings_new = constructor_standings.copy()
clean_backslash_n(constructor_standings_new)

,constructorStandingsId,raceId,constructorId,points,position,positionText,wins
0,1,18,1,14.0,1,1,1
1,2,18,2,8.0,3,3,0
2,3,18,3,9.0,2,2,0
3,4,18,4,5.0,4,4,0
4,5,18,5,2.0,5,5,0
...,...,...,...,...,...,...,...
13386,28978,1144,15,4.0,10,10,0
13387,28979,1144,210,58.0,7,7,0
13388,28980,1144,215,46.0,8,8,0
13389,28981,1144,3,17.0,9,9,0
13390,28982,1144,214,65.0,6,6,0

In [9]:
# 4. constructors.csv
# No need of 'url'


constructors_new = constructors.copy()
constructors_new.drop(columns=['url'], inplace=True)
clean_backslash_n(constructors_new)

     constructorId constructorRef            name nationality
0                1        mclaren         McLaren     British
1                2     bmw_sauber      BMW Sauber      German
2                3       williams        Williams     British
3                4        renault         Renault      French
4                5     toro_rosso      Toro Rosso     Italian
..             ...            ...             ...         ...
207            210           haas    Haas F1 Team    American
208            211   racing_point    Racing Point     British
209            213     alphatauri      AlphaTauri     Italian
210            214         alpine  Alpine F1 Team      French
211            215             rb      RB F1 Team     Italian

[212 rows x 4 columns]

In [10]:
# 5. driver_standings.csv
# Nothing to change here!


driver_standings_new = driver_standings.copy()
clean_backslash_n(driver_standings_new)

,driverStandingsId,raceId,driverId,points,position,positionText,wins
0,1,18,1,10.0,1,1,1
1,2,18,2,8.0,2,2,0
2,3,18,3,6.0,3,3,0
3,4,18,4,5.0,4,4,0
4,5,18,5,4.0,5,5,0
...,...,...,...,...,...,...,...
34858,73266,1144,858,0.0,23,23,0
34859,73267,1144,860,7.0,18,18,0
34860,73268,1144,861,5.0,19,19,0
34861,73269,1144,859,4.0,21,21,0
34862,73270,1144,862,0.0,24,24,0

In [11]:
# 6. drivers.csv
# Drop 'url' and replace '\N' with 'NA'


drivers_new = drivers.copy()
drivers_new['number'] = drivers_new['number'].replace('\\N', 'NA')
drivers_new.drop(columns=['url'], inplace=True)
clean_backslash_n(drivers_new)

,driverId,driverRef,number,code,forename,surname,dob,nationality
0,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British
1,2,heidfeld,NA,HEI,Nick,Heidfeld,1977-05-10,German
2,3,rosberg,6,ROS,Nico,Rosberg,1985-06-27,German
3,4,alonso,14,ALO,Fernando,Alonso,1981-07-29,Spanish
4,5,kovalainen,NA,KOV,Heikki,Kovalainen,1981-10-19,Finnish
...,...,...,...,...,...,...,...,...
856,858,sargeant,2,SAR,Logan,Sargeant,2000-12-31,American
857,859,lawson,30,LAW,Liam,Lawson,2002-02-11,New Zealander
858,860,bearman,38,BEA,Oliver,Bearman,2005-05-08,British
859,861,colapinto,43,COL,Franco,Colapinto,2003-05-27,Argentinian
860,862,doohan,61,DOO,Jack,Doohan,2003-01-20,Australian

In [12]:
# 7. lap_times.csv
# Nothing to change here!
lap_times_new = lap_times.copy()
clean_backslash_n(lap_times_new)

# 8. pit_stops.csv
# Nothing to change here!
pit_stops_new = pit_stops.copy()
clean_backslash_n(pit_stops_new)

       raceId  driverId  stop  lap      time duration  milliseconds
0         841       153     1    1  17:05:23   26.898         26898
1         841        30     1    1  17:05:52   25.021         25021
2         841        17     1   11  17:20:48   23.426         23426
3         841         4     1   12  17:22:34   23.251         23251
4         841        13     1   13  17:24:10   23.842         23842
...       ...       ...   ...  ...       ...      ...           ...
11366    1144       840     2   32  17:52:48   22.053         22053
11367    1144         1     1   34  17:55:17   21.694         21694
11368    1144         4     2   37  18:00:10   22.437         22437
11369    1144       855     2   39  18:03:21   28.765         28765
11370    1144       825     4   55  18:28:06   22.090         22090

[11371 rows x 7 columns]

In [13]:
# 9. qualifying.csv
# Handling null values


qualifying_new = qualifying.copy()

qualifying_new['q2'] = qualifying_new['q2'].fillna("NA")
qualifying_new['q3'] = qualifying_new['q3'].fillna("NA")

clean_backslash_n(qualifying_new)

,qualifyId,raceId,driverId,constructorId,number,position,q1,q2,q3
0,1,18,1,1,22,1,1:26.572,1:25.187,1:26.714
1,2,18,9,2,4,2,1:26.103,1:25.315,1:26.869
2,3,18,5,1,23,3,1:25.664,1:25.452,1:27.079
3,4,18,13,6,2,4,1:25.994,1:25.691,1:27.178
4,5,18,2,2,3,5,1:25.960,1:25.518,1:27.236
...,...,...,...,...,...,...,...,...,...
10489,10547,1144,848,3,23,16,1:23.821,NA,NA
10490,10548,1144,855,15,24,17,1:23.880,NA,NA
10491,10549,1144,1,131,44,18,1:23.887,NA,NA
10492,10550,1144,861,3,43,19,1:23.912,NA,NA
10493,10551,1144,862,214,61,20,1:24.105,NA,NA

In [14]:
# 10. races.csv
# Dropping these columns 'time, url, fp1_time, fp2_time, fp3_time, quali_time, sprint_time'


races_new = races.copy()
clean_backslash_n(races_new)
races_new.drop(columns=['time', 'url', 'fp1_time', 'fp2_time', 'fp3_time', 'quali_time', 'sprint_time'], inplace=True)

In [15]:
# 11. results.csv
# Handling Null values

results_new = results.copy()
clean_backslash_n(results_new)

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId
0,1,18,1,1,22,1,1,1,1,10.0,58,1:34:50.616,5690616,39,2,1:27.452,218.300,1
1,2,18,2,2,3,5,2,2,2,8.0,58,+5.478,5696094,41,3,1:27.739,217.586,1
2,3,18,3,3,7,7,3,3,3,6.0,58,+8.163,5698779,41,5,1:28.090,216.719,1
3,4,18,4,4,5,11,4,4,4,5.0,58,+17.181,5707797,58,7,1:28.603,215.464,1
4,5,18,5,1,23,3,5,5,5,4.0,58,+18.014,5708630,43,1,1:27.418,218.385,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26754,26760,1144,825,210,20,14,16,16,16,0.0,57,NA,NA,57,1,1:25.637,222.002,11
26755,26761,1144,859,215,30,12,17,17,17,0.0,55,NA,NA,52,12,1:28.751,214.212,5
26756,26762,1144,822,15,77,9,NA,R,18,0.0,30,NA,NA,14,19,1:29.482,212.462,130
26757,26763,1144,861,3,43,20,NA,R,19,0.0,26,NA,NA,5,17,1:29.411,212.631,5
26758,26764,1144,815,9,11,10,NA,R,20,0.0,0,NA,NA,NA,0,NA,NA,4

In [16]:
# 12. seasons.csv
# Handling '\N' values


seasons_new = seasons.copy()
clean_backslash_n(seasons_new)
seasons_new.drop(columns='url', inplace=True)

In [17]:
# 12. sprint_results.csv
# Handling '\N' values 


sprint_results_new = sprint_results.copy()
clean_backslash_n(sprint_results_new)

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,fastestLapTime,statusId
0,1,1061,830,9,33,2,1,1,1,3,17,25:38.426,1538426,14,1:30.013,1
1,2,1061,1,131,44,1,2,2,2,2,17,+1.430,1539856,17,1:29.937,1
2,3,1061,822,131,77,3,3,3,3,1,17,+7.502,1545928,17,1:29.958,1
3,4,1061,844,6,16,4,4,4,4,0,17,+11.278,1549704,16,1:30.163,1
4,5,1061,846,1,4,6,5,5,5,0,17,+24.111,1562537,16,1:30.566,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
355,356,1143,859,215,30,10,16,16,16,0,19,+34.356,1657366,18,1:25.762,1
356,357,1143,852,215,22,16,17,17,17,0,19,+35.102,1658112,17,1:25.838,1
357,358,1143,861,3,43,0,18,18,18,0,19,+35.639,1658649,18,1:25.599,1
358,359,1143,855,15,24,18,19,19,19,0,19,+1:11.436,1694446,19,1:25.051,1
359,360,1143,815,9,11,0,20,20,20,0,19,+1:14.371,1697381,18,1:24.892,1

In [18]:
# status.csv
# Nothing to change here!
status_new = status.copy()
clean_backslash_n(status_new)

     statusId          status
0           1        Finished
1           2    Disqualified
2           3        Accident
3           4       Collision
4           5          Engine
..        ...             ...
134       137          Damage
135       138          Debris
136       139         Illness
137       140       Undertray
138       141  Cooling system

[139 rows x 2 columns]

In [19]:
# Saving cleaned datasets

circuits_new.to_csv('Cleaned_datasets/circuits_cleaned.csv', index=False)
constructor_results_new.to_csv('Cleaned_datasets/constructor_results_cleaned.csv', index=False)
constructor_standings_new.to_csv('Cleaned_datasets/constructor_standings_cleaned.csv', index=False)
constructors_new.to_csv('Cleaned_datasets/constructors_cleaned.csv', index=False)
driver_standings_new.to_csv('Cleaned_datasets/driver_standings_cleaned.csv', index=False)
drivers_new.to_csv('Cleaned_datasets/drivers_cleaned.csv', index=False)
lap_times_new.to_csv('Cleaned_datasets/lap_times_cleaned.csv', index=False)
pit_stops_new.to_csv('Cleaned_datasets/pit_stops_cleaned.csv', index=False)
qualifying_new.to_csv('Cleaned_datasets/qualifying_cleaned.csv', index=False)
races_new.to_csv('Cleaned_datasets/races_cleaned.csv', index=False)
results_new.to_csv('Cleaned_datasets/results_cleaned.csv', index=False)
seasons_new.to_csv('Cleaned_datasets/seasons_cleaned.csv', index=False)
sprint_results_new.to_csv('Cleaned_datasets/sprint_results_cleaned.csv', index=False)
status_new.to_csv('Cleaned_datasets/status_cleaned.csv', index=False)